#!/usr/bin/env bash
# Gradle wrapper script for Windows (simplified)
# This file would normally be generated by gradle wrapper task

GRADLE_HOME="$HOME/.gradle/wrapper/dists/gradle-8.5-bin"

if [ ! -d "$GRADLE_HOME" ]; then
    echo "Gradle not found, downloading..."
    # In production, this would download gradle
fi

exec gradle "$@"
