# SWMPartyGame 配置

swm:
  world_folder: "./swm_worlds/"

# 遊戲配置
games:
  - id: "partygame"
    name: "Party Game"
    min_players: 4
    max_players: 8

# 後端配置
backend:
  id: "backend1"
  redis:
    channel: "partygame:backend"
  
hotreload:
  enabled: true
  interval: 5
